import "@/app/globals.css";
import Navigation from "@/components/layout/Navigation";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=" bg-slate-900">
        <Navigation />
        {children}
        </body>
    </html>
  )
}
